apiVersion: v1
kind: Secret
metadata:
  name: kapp-controller-config
  namespace: tkg-system
stringData:
  caCerts: |-
    -----BEGIN CERTIFICATE-----
    MIIDZDCCAkygAwIBAgIUJccwIS9iYkjb/TIjCp7huYSeVj4wDQYJKoZIhvcNAQEL
    BQAwJTEjMCEGA1UEAxMaaDJvLTQtMjIzODguaDJvLnZtd2FyZS5jb20wHhcNMjQw
    MjIyMDA0MzMzWhcNMzQwMjE5MDA0NDAzWjAlMSMwIQYDVQQDExpoMm8tNC0yMjM4
    OC5oMm8udm13YXJlLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
    AMaiT7dKhsld3f8zbsoQkBgw+Dz3ML3U37kL1GxiDSbn3aZBb71In703rw2czOmL
    xe9oXmFq6v81i1/2HIUX5iHUYSh/UaSFA7+KU9j1E2nF0FxwivRQQCgVDOtqZeL9
    J22GpkP91jXRVjo5Gc36pOXIXczzv/bRlO/PuhiGdUlKVtOtWInpiQi2WeVkOdj/
    PeQzke//Cr68WqG4XOP2z3RglPbn0K88Ws0YHkEdgB2wF26YFZDcuyoqvQFsr2lD
    dKmvcAwCpTUBBi9MpLAx3UFrMTwDMAIZhKoOpG9DxKXIjW9d/MXF6xCN9yIgEqrx
    Wa5AHj9dM+0xgazZnApuF2UCAwEAAaOBizCBiDAOBgNVHQ8BAf8EBAMCAQYwDwYD
    VR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUB7x3WBWxF7yefuxsVa7CpM21F38wHwYD
    VR0jBBgwFoAUB7x3WBWxF7yefuxsVa7CpM21F38wJQYDVR0RBB4wHIIaaDJvLTQt
    MjIzODguaDJvLnZtd2FyZS5jb20wDQYJKoZIhvcNAQELBQADggEBAEKxOJxvBErt
    OzyVJ1E6UfwZAvnLSO8PI8NKaxqEBthoQUs2L4fhk9z3vC/NpD7upFZMKwdou82i
    FiWd7iXnmqT9fp4dYCRAIhp1Jlnz/emEqnPLWQbwwjEuQoSqFGWB3XPCu9orxzul
    FhAYyKDrOpYaaaXSeJQaumOoEzZ94MB4iHjPe+W3yD1Sd16RN5xZx/GehNM/6vU0
    Bb431+fIibn7Co+kxRWvJkxl2qu1budTu1LUlQ0XRnYWcrGdY96rptGwKElzMo6E
    e9JrE/JLom3RXClafauY6NYM8AxQG74lt+wT7BSbNPflY8i6r8D8IwR8GWCjXAsr
    FlnIzdIFF2A=
    -----END CERTIFICATE-----
