apiVersion: ENC[AES256_GCM,data:ZYQ=,iv:Q8Lv5vrebGebHtz2U9WdRLjtkSVWzMAPcm2anW8zK5A=,tag:sycRtaTMsiCQ2sCujlfQPg==,type:str]
kind: ENC[AES256_GCM,data:sL4k0KVd,iv:QFb466guXhZ/I0HMOCyizv+1l7wyStlttVCRUAEhEdE=,tag:kTt9U7w8BBh/btnpkR52KQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:d53ACACVEGMZYbFqMXE=,iv:RHdYEYFNR7B/tvtfyBY9AOME3v5MLWcY9kxYeA1SZ8M=,tag:xNjZ6huy9ieCO2uuUsGVqw==,type:str]
    namespace: ENC[AES256_GCM,data:GvpKoeZfvwyPlhs=,iv:L6vdtTJ7L7CQqd8pKjDEncgjT9mMyUyBsPis0/KDnec=,tag:a5edGx8dZePwzgbZYV4UVg==,type:str]
type: ENC[AES256_GCM,data:WZKzakMdlk7rJMHBnW+zB+oIRu2oTMAo7RUAZhwP,iv:/eD8Q3BgU4Dc2vyHWzThpVx2zLpV6oUN92q0Bp+xwiU=,tag:FeSd/E4a+Xx5xiLZ7EU6lA==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:ZxXiVBvhieuyfEdOnUWyiRWcgdvG3YAToR+7CANj7dA33IVb6OoFXibgV4NwrWYurltY+now79iOiAz4Jzet/z9EjyVYYH9/jjghNY/vYZ5zNmLEDoOtGn10bprLDgJXnwvpoKaMQVeHKRrvjzjOfZyxxcG1AEz5,iv:GYvxAFvfBPuK67oP0g+SgrH6GHPn1Kh2YRVcbGWklvw=,tag:ReMS3brnQgiim3r018arNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxjylrjqxk490snley8rjyyfx5wp35gavqct38l9e84l0lxdfd7q9yfh0d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWFpkb3REajVhYW1yWkZ1
            MGZvNkN4T1ZPbVhWc2tmRGlsc1RTL0VLQUVVCnhHRUNyN0dKbXd6aFRwSW5iZi84
            WnBHaDZzUDUzRmtkYWR0SU5VWVBQV0kKLS0tIENzM0F6WkR5eWlvV3Q3L2pleEw3
            bko2RFE0OHVrUGExUnR0dm54cGRBUEkKNydm3Tl0/0Ozft235PQnTn3bY/UBbNz0
            bHK6E24sVllpfq4Gfw80haM1hF7L+FicS7gONMh5wb6sAWItTAjuNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-27T16:55:28Z"
    mac: ENC[AES256_GCM,data:OU3PUtkCVXR4bL7bFT4edQFww/xWby248xU387d7qYOTvFlksbcfLQmB0n4HVTAywLMucUOqwuk8IJvLcd1TFkS7XvwZ96xDeJ2i9TVCWPwWA+Quv6NNikM0zFHrOIyYZh0fPguXaMAtUHGVg+LYJYtKpMxwvETMimji1eSEA34=,iv:OVwXS6UvybmNfFntwD9YHAEhy0oPrSSiffHIrY7Iaas=,tag:x0OkJ+b2/5LdcuDlSN7RWw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
