apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-cert
  namespace: tanzu-system-registry
spec:
  secretName: harbor-cert
  issuerRef:
    kind: ClusterIssuer
    name: vault-cluster-issuer
  commonName: harbor.h2o-4-22388.h2o.vmware.com
  dnsNames:
  - harbor.h2o-4-22388.h2o.vmware.com
