#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  name: platform-user-trusted-ca-secret
  namespace: platform
data:
  #! Double encoded to work around bug: https://jira.eng.vmware.com/browse/GCM-6737
  vault-ca: #@ base64.encode(base64.encode(data.values.harbor.platform.tls.ca))
type: Opaque