apiVersion: v1
kind: Secret
metadata:
  name: contour-data-values
  namespace: package-installs
type: Opaque
stringData:
  values.yml: |
    envoy:
      service: 
        type: LoadBalancer
        externalTrafficPolicy: Local