apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-vault-token
  namespace: cert-manager
  annotations:
    kubernetes.io/service-account.name: issuer
type: kubernetes.io/service-account-token