apiVersion: v1
kind: Namespace
metadata:
  name: package-installs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: package-install-sa
  namespace: package-installs
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: package-install-sa
subjects:
- kind: ServiceAccount
  name: package-install-sa
  namespace: package-installs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzupackage-install-admin-role