apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spring-petclinic-gateway-cert
  namespace: spring-petclinic
spec:
  dnsNames:
  - petclinic.platform.h2o-4-22388.h2o.vmware.com
  secretName: spring-petclinic-gateway-tls-cert
  issuerRef:
    name: vault-cluster-issuer
    kind: ClusterIssuer
