secrets:
    sops:
        age_key: ENC[AES256_GCM,data:Z/coxjdrGrmfJWyhOXIJp3Iqf/jh+XcAtke3Ij+D8Y5y6ExSid1DdXCYLCX/ABEYvYep2aH/xwiMrjYrux10B0RApAUFRQSO0hA=,iv:mtN2Fsw0nY1RGBRd08T802cdAnFmfXt5DSIYwGK7QTw=,tag:LU+A9z7yfC6+FFUqwAs+tA==,type:str]
        registry:
            hostname: ENC[AES256_GCM,data:2jwG5biulSuGnV6Szj79ZrvNfwU7kavIhQ==,iv:D+SMq5DRa8uC3Mg3jHXdAagG0mxFj7wh+jGgpmsxi20=,tag:zUWVRv0lW1k5HhtC7xSYZA==,type:str]
            username: ENC[AES256_GCM,data:W+NYwMRJl1AKtvUYzHOl7tbNdw==,iv:QQ5xj/8voOYdM01onExw23btF5/Gy/Nlvo9mFl7Zo6w=,tag:sB+k2COttzbv2nKsI/H7/A==,type:str]
            password: ENC[AES256_GCM,data:fmCStD4l91zJTPsu0g==,iv:elBENUOpg3Ho+FrW6Iq1gHw5C+gt2C31uHsUW641Z0w=,tag:lCWLloR0Go/8PVFC0bYcdQ==,type:str]
        git:
            basic_auth:
                username: ENC[AES256_GCM,data:CZVmiwZE2Q==,iv:Vq7/zg26NayKKY54xCjnw9iOFhKjB7Ne1afgxM4WkEU=,tag:R94eeNPVavIuET5djJUX7w==,type:str]
                password: ENC[AES256_GCM,data:IIiBD2GrIJUQHI0uYQL8UpOk35aJ9VRD93Hefen9xoxhEkW60Z4ZGw==,iv:090DC4R7rXqjq9oy/0f8Ljjj+MJorV1DAg/jDvaa0nQ=,tag:bF6kPWpKdp4jy0bDghLgPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxjylrjqxk490snley8rjyyfx5wp35gavqct38l9e84l0lxdfd7q9yfh0d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZGhMMFJrU0NaMVlKa3Nw
            SDMwdmNjS0tXSW5ueU9xZ0dhK0RrN1ZGOEJRCktqM0JZa1h0RENIaFJWdlNiS05k
            WVg2N0NCTnBXV0V3SmhwVmk0OVo2TW8KLS0tIGJ0RWZiMWI3b1dpMG44bTB4emZX
            MGNtQkdGL1BiT2twV1FYdmcwR2lhOHMKIdMx5D98eJMCuwXuSfGlellUIzRuHbcl
            zrgKZyUtowJnk/wFC/1PbKgK9uLIAm/ZnKfAfkJDKcUfk8RCNV45KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-27T21:55:17Z"
    mac: ENC[AES256_GCM,data:9BdX+zl3CvfkvL4pHNWmH8f+YqFzZtAuDBJOd0t3n8DimBTK9ZpJ1E0EsFELTBaImwwvn0lsEpn8TkTuc9YAXCx/fXpOxvXrczleENeqriw1Jla037wb5F2ZFy59S9P+a7d6G/h66w3lm/GDQWMCDaNjCLTmqllGZUX4CX1ZdE4=,iv:kMOCTfEH5qzBe45cD84TfRZ84f6F5jJLtPjIzOUQ5jE=,tag:xwR4YMQh+5rzw8QPPaxSZg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
