apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: actual-vault-cluster-issuer
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
  - name: cert-manager
  - name: cluster-group-bootstrap-resources
  - name: vault-cluster-issuer
  interval: 5m
  path: ./clusters/platform/hydration/vault-cluster-issuer
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-gitops-cluster-level
