apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: contour
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: cluster-group-bootstrap-resources
    - name: cert-manager
  interval: 5m
  path: "./hydration/contour/base"
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-gitops-cluster-level
  healthChecks:
    - apiVersion: packaging.carvel.dev/v1alpha1
      kind: PackageInstall
      name: contour
      namespace: package-installs