apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: sandbox-1
  namespace: sandbox
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 172.20.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
        - 10.96.0.0/16
  topology:
    class: tanzukubernetescluster
    controlPlane:
      metadata: {}
      replicas: 1
    variables:
      - name: defaultStorageClass
        value: vc01cl01-t0compute
      - name: vmClass
        value: best-effort-medium
      - name: storageClass
        value: vc01cl01-t0compute
      - name: storageClasses
        value:
          - vc01cl01-t0compute
    version: v1.25.7+vmware.3
    workers:
      machineDeployments:
        - class: node-pool
          metadata: {}
          name: md-0
          replicas: 3
          variables:
            overrides:
              - name: vmClass
                value: best-effort-medium
              - name: storageClass
                value: vc01cl01-t0compute
