apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: cluster-group-bootstrap-resources
  interval: 5m
  path: "./hydration/cert-manager/base"
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-gitops-cluster-level
  healthChecks:
    - apiVersion: packaging.carvel.dev/v1alpha1
      kind: PackageInstall
      name: cert-manager
      namespace: package-installs
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-cluster-issuer
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: cert-manager
  interval: 5m
  path: "./hydration/vault-cluster-issuer/base"
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-gitops-cluster-level