apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-portal-tls-cert.yaml
  namespace: api-portal
spec:
  dnsNames:
  - api-portal.tap.h2o-4-22388.h2o.vmware.com
  secretName: api-portal-tls-cert
  issuerRef:
    name: vault-cluster-issuer
    kind: ClusterIssuer
