apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: developer-defined-tekton-pipeline-node
  labels:
    apps.tanzu.vmware.com/pipeline: test-node
spec:
  params:
  - name: source-url
  - name: source-revision
  - name: source-sub-path
    default: ""
  tasks:
  - name: test
    params:
    - name: source-url
      value: $(params.source-url)
    - name: source-revision
      value: $(params.source-revision)
    - name: source-sub-path
      value: $(params.source-sub-path)
    taskSpec:
      params:
      - name: source-url
      - name: source-revision
      - name: source-sub-path
      steps:
      - name: test
        image: harbor.h2o-4-22388.h2o.vmware.com/tap/tekton/circleci/node:14-browsers
        script: |-
          cd `mktemp -d`

          wget -qO- $(params.source-url) | tar xvz -m

          SUB_PATH=$(params.source-sub-path)
          if [ -z ${SUB_PATH:-""} ]; then
            echo "INFO: No subpath provided."
          else
            echo "INFO: Changing directory to $SUB_PATH"
            cd $SUB_PATH
          fi
          export CI=true
          npm install
          npm run test
