apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-pipeline-skip
  labels:
    apps.tanzu.vmware.com/pipeline: test-skip
  annotations:
    kapp.k14s.io/create-strategy: fallback-on-update
spec:
  params:
  - name: source-url
  - name: source-revision
  tasks:
  - name: test
    params:
    - name: source-url
      value: $(params.source-url)
    - name: source-revision
      value: $(params.source-revision)
    taskSpec:
      params:
      - name: source-url
      - name: source-revision
      steps:
      - name: test
        image: harbor.h2o-4-22388.h2o.vmware.com/tap/tekton/alpine
        script: |-
          echo "Skipping tests"
          exit 0
